apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: ClusterIP
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1 # Specifies the number of instances
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      serviceAccountName: demo
      containers:
        - name: demo
          image: docker.io/linsun/demo:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: OLLAMA_BASE_URL
              value: "http://host.docker.internal:11434"
              # value: "http://ollama:80"
            # - name: SECRET_OPENAI
              # valueFrom:
              #   secretKeyRef:
              #     name: openai
              #     key: key
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1